version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "75:a0:b8:08:6b:f8:68:0c:58:1d:93:22:f9:fc:18:a5"
      - checkout
      - run:
          name: install
          command: npm install
      - run: npm run commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release -- --debug
